
# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Bug fixes 🛠
      labels:
        - bug
    - title: Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"