# More documentation here
# https://docs.github.com/en/actions
---
name: Create new release


on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'app_version eg: 3.4.1'
        required: true
        type: string

env:
  ENV_1: X

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
