# More documentation here
# https://docs.github.com/en/actions
---
name: Create new release


on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'app_version eg: 1.2.3'
        required: true
        type: string

env:
  ENV_1: X

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    needs: [bump-version]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git tag ${{ github.event.inputs.app_version }}
          git push origin ${{ github.event.inputs.app_version }}

  generate-release:
    runs-on: ubuntu-latest
    needs: generate-tag
    steps:
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.app_version }}"
          title: "v${{ github.event.inputs.app_version }}"
          prerelease: false
