# More documentation here
# https://docs.github.com/en/actions
---
name: Create new release


on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'app_version eg: 1.2.3'
        required: true
        type: string

env:
  ENV_1: X

jobs:
  remove-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Remove branch protection
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.PAT }}"
          script: |
            github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: "main",
              required_status_checks: null,
              enforce_admins: null,
              required_pull_request_reviews: null,
              restrictions: null,
            })

  bump-version:
    runs-on: ubuntu-latest
    needs: remove-branch-protection
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          > VERSION.md
          echo "${{ github.event.inputs.app_version }}" > VERSION.md
          git add .
          git commit -m "Bump version to ${{ github.event.inputs.app_version }}"
          git push origin ${GITHUB_REF##*/}
  
  add-branch-protection:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Add branch protection
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.PAT }}"
          script: |
            github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: "main",
              required_status_checks: null,
              enforce_admins: null,
              required_pull_request_reviews: {},
              restrictions: null,
            })

  generate-tag:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull
        run: git pull origin ${GITHUB_REF##*/}
      - name: Generate tag
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git tag ${{ github.event.inputs.app_version }}
          git push origin ${{ github.event.inputs.app_version }}

  generate-release:
    runs-on: ubuntu-latest
    needs: generate-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release notes
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.event.inputs.app_version }}",
              name: "${{ github.event.inputs.app_version }}",
              generate_release_notes: true
            })
  
  comment-on-each-pr:
    runs-on: ubuntu-latest
    needs: generate-release
    steps:
      - name: Comment on each PR
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "${{ github.event.inputs.app_version }}"
            })
            const body = release.data.body
            const strings = body.split('\n')
            const prs = strings.filter(i => i.includes('/pull/'))
            const pr_ids = prs.map(i => i.split('/pull/').pop())
            const unique_pr_ids = pr_ids.filter((v, i, a) => pr_ids.indexOf(v) === i)
            unique_pr_ids.map(id => {
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: id,
                body: "This PR has been included in version [${{ github.event.inputs.app_version }}](https://github.com/paulo9mv/release-notes/releases/tag/${{github.event.inputs.app_version}}) 🎉"
              })
            })
