---
name: Security

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  comment-on-each-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on each PR
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: id,
                body: "This PR has been included in version 🎉"
              })
